name: Setup code workspace ⚙️
description: 'Setup code workspace for testing and code quality checks'

inputs:
  node-version:
    required: false
    type: string
    default: '22'
  os:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup Node version ⚙️
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        cache: yarn
        cache-dependency-path: 'yarn.lock'
        node-version: ${{ inputs.node-version }}

    - name: Restore cached node modules ♻️
      id: cache-yarn
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          .yarn/cache
          node_modules
        key: ${{ inputs.os }}-${{ inputs.node-version }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ inputs.os }}-${{ inputs.node-version }}-build

    - name: Install dependencies 🔧
      if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
      run: yarn install --immutable
      shell: bash
