name: 'Questions / Help 💬'
description: If you have questions, please check Reactiflux or StackOverflow
title: '[Please read the message below]'
labels: ['💬 Question']
body:
  - type: markdown
    attributes:
      value: |
        ## Questions and Help 💬

        This issue tracker is reserved for bug reports and feature proposals.

        For anything else, such as questions or getting help, please see:

        - [The Jest help page](https://jestjs.io/help)
        - Our [online documentation](https://thymikee.github.io/jest-preset-angular/)
        - [Our `#testing` channel in Reactiflux](https://discord.gg/j6FKKQQrW9)
        - The [jestjs](https://stackoverflow.com/questions/tagged/jestjs) tag on [StackOverflow](https://stackoverflow.com/questions/ask)
        - The [jest-preset-angular](https://stackoverflow.com/questions/tagged/jest-preset-angular) tag on [StackOverflow](https://stackoverflow.com/questions/ask)
  - type: checkboxes
    id: no-post
    attributes:
      label: |
        Please do not submit this issue.
      description: |
        :bangbang: &nbsp; This issue will be closed. :bangbang:
      options:
        - label: I understand
          required: true
