// BannerComponent as initially generated by the CLI
import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
    selector: 'app-banner',
    template: '<p>banner works!</p>',
    changeDetection: ChangeDetectionStrategy.OnPush,
    styles: [],
})
export class BannerComponent {}
