// Reduced version of the initial AppComponent generated by CLI
import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
    selector: 'app-root',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: '<h1>Welcome to {{title}}!</h1>',
})
export class AppInitial {
    title = 'app';
}
