name: Setup documentation workspace ⚙️

inputs:
  base-url:
    required: false
    type: string
    default: '/jest-preset-angular/'

runs:
  using: composite
  steps:
    - name: Setup Node version ⚙️
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        cache: yarn
        cache-dependency-path: 'website/yarn.lock'
        node-version: 24.14.1

    - name: Restore cached node modules ♻️
      id: cache-yarn
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: |
          website/.yarn/cache
          website/node_modules
        key: node-22-website-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: node-22-website-build

    - name: Install dependencies 🔧
      run: yarn install --frozen-lockfile
      shell: bash
      working-directory: website

    - name: Build 🔧
      run: yarn build
      shell: bash
      env:
        BASE_URL: ${{ inputs.base-url }}
      working-directory: website
