name: Setup documentation workspace ⚙️

inputs:
  baseURL:
    required: false
    type: string
    default: '/jest-preset-angular/'

runs:
  using: composite
  steps:
    - name: Setup Node version ⚙️
      uses: ./.github/actions/setup-node
      with:
        cache-dependency-path: 'website/yarn.lock'

    - name: Install 🔧
      run: yarn install --frozen-lockfile
      shell: bash
      working-directory: website

    - name: Build 🔧
      run: yarn build
      shell: bash
      env:
        BASE_URL: ${{ inputs.baseURL }}
      working-directory: website
