name: PR codes check 🔍

on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*'
      - '!website/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 22.x, 24.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace for ${{ matrix.os }} on Node v${{ matrix.node-version }} ⚙️
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

  test-code-quality:
    needs: prepare-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace ⚙️
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Run check commit convention 🔍️
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run ESLint check 🔍️
        run: yarn lint

      - name: Run Prettier check 🔍️
        run: yarn lint-prettier-ci

  test:
    needs: prepare-cache
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 22.x, 24.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace ⚙️
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Run unit tests 🧪
        run: yarn test

      - name: Run e2e tests 🧪
        run: yarn test-e2e

      - name: Run tests in example projects 🧪
        run: yarn test-examples

  test-performance:
    needs: prepare-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace ⚙️️
        uses: ./.github/actions/setup-codespace
        with:
          os: ${{ runner.os }}

      - name: Build 🏗️
        run: yarn build

      - name: Install dependencies 📦
        run: yarn --cwd performance

      - name: Run Performance Tests 🧪
        run: yarn test-perf
