name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup Node version ⚙️
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          cache: yarn
          cache-dependency-path: 'yarn.lock'
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Build 🔨
        run: yarn build

      - name: Create release 🚀
        run: npm publish
