name: Source codes CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare_cache_ubuntu:
    strategy:
      matrix:
        node: [18.x, 20.x]
    uses: ./.github/workflows/install.yml
    with:
      os: ubuntu-latest
      node: ${{ matrix.node }}

  prepare_cache_windows:
    strategy:
      matrix:
        node: [18.x, 20.x]
    uses: ./.github/workflows/install.yml
    with:
      os: windows-latest
      node: ${{ matrix.node }}

  code_standard_check:
    needs: prepare_cache_ubuntu
    uses: ./.github/workflows/code_standard_check.yml
    with:
      os: ubuntu-latest
      node: 20.x

  test_windows:
    needs: prepare_cache_windows
    strategy:
      matrix:
        node: [18.x, 20.x]
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest
      node: ${{ matrix.node }}

  test_ubuntu:
    needs: prepare_cache_ubuntu
    strategy:
      matrix:
        node: [18.x, 20.x]
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
      node: ${{ matrix.node }}
