name: Target branch check 🔍

on:
  push:
    branches:
      - main
      - next
    paths:
      - '**/*'
      - '!website/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-merged-branch:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x, 24.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace for ${{ matrix.os }} on Node v${{ matrix.node-version }} ⚙️
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Run tests in CommonJS mode 🧪
        run: yarn test

      - name: Run tests in ESM mode 🧪
        run: yarn test-esm

      - name: Run tests in example projects 🧪
        run: yarn test-examples
